### ISSUE TITLE
Group 1 in some tilesets is unfinished and displays odd textures

### ISSUE THREAD

**Issue by echkode** [BraceYourselfGames/PB_ModSDK#1]
**Describe the bug**
Tilesets like industrial (10) have a group 1 that's showing odd textures. This looks like an unfinished group or something changed since it was created.

**To Reproduce**
1. Go to the Combat\Areas config DB and select an area
2. Open the level editor and choose the spot editing mode
3. Move to a floor surface (configuration 0000_1111) for a spot with the industrial tileset
4. Use shift + mouse wheel to select group 1
5. An odd looking tile will appear

**Expected behavior**
A tile that has a texture that matches the surroundings.

**Screenshots**
![odd_textures_more](https://github.com/BraceYourselfGames/PB_ModSDK/assets/48565771/98554164-1e56-4cff-a641-d01d745bf4bb)

**System (please confirm the following information):**
 - Windows 10
 - 2020.3.34f1

**Comment by artyom-zuev** [comment]
Yay, first issue in history! Thank you so much for spotting this, looks like we have the same bug internally and would benefit from the fix even outside the SDK!
